### ISSUE TITLE
The template does not work properly anymore

### ISSUE THREAD

**Issue by akarsh** [BlackrockDigital/startbootstrap-freelancer#104]
I used the template for creating my github page.
project repo: https://github.com/akarsh/akarsh.github.io
http://akarsh.github.io/

But today i made a small change & the whole page looks disoriented.
Can you please help me fix it. as in my locacl machine it shows properly.  After commit to github, it shows the page disoriented from design

**Comment by davidtmiller** [comment]
Check to make sure that your Bootstrap CSS is loading properly. What you're seeing is what happens when the Bootstrap core CSS files don't load up. Hopefully this helps!

**Comment by TheLegitHabibi** [comment]
I'd like to know how to fix this too. 
Facing the exact same problem here.

**Comment by akarsh** [comment]
I update the base templates matching to the changes of the commit https://github.com/BlackrockDigital/startbootstrap-freelancer/commit/e72d0712aad1e7995747d0f4e50127a4809620d2 
with mine 
https://github.com/akarsh/akarsh.github.io/commit/826f13641a8969f2e30c58a3e94df976b92b90c1

But, i did not figure out the core css changes.  I saw the version changes from 3.3.6 to 3.3.7
Any way to fix it ?

**Comment by akarsh** [comment]
I forked the repository & only changed the repo name https://akarsh.github.io/
But the css issue is the same
