### ISSUE TITLE
Its all bugged out?

### ISSUE THREAD

**Issue by TheLegitHabibi** [BlackrockDigital/startbootstrap-freelancer#105]
There's something wrong with the theme. I just cloned everything you had and this is what the page looks like:

http://image.prntscr.com/image/8229d998c12045969d99362330697b21.png

Its all bugged out. I'm very very new to HTML and CSS so I don't know what's wrong.

**Comment by TheLegitHabibi** [comment]
So apparently the issue is that the bootstrap core CSS files won't load. 
Why won't they since last night? Pls help newbie.

**Comment by Prime1337** [comment]
Same thing happened in my case. I'd like to know how to fix boostrap core so It will load along with your template.

**Comment by davidtmiller** [comment]
I am not sure with this one, everything should be included with the package. Make sure that the core files are loading in your HTML. Troubleshoot it in the browser and see if the file path is correct and that nothing is changed. If that doesn't work try to re-download the package and try again.

Other than that everything seems to work in the theme, so hopefully this helps!

**Comment by TheLegitHabibi** [comment]
Apparently Github was causing issues because of the "Vendor" name. So renaming it fixed it for me.
