### ISSUE TITLE
Problem with github.io

### ISSUE THREAD

**Issue by nemanja-rakicevic** [BlackrockDigital/startbootstrap-freelancer#107]
Hello,
I've downloaded the project and edited the section in html, as well as the css files, and changed the path to use .css instead of .min.css. Afterwards, when I push it to my github repository and try to open the website, it is not responsive anymore and seems that all styling is not working.

Has anyone had a similar problem?
Is there some mistake in the steps I made?

**Comment by vrialland** [comment]
Seems like there is something wrong with the vendor folder, files are present on the repo but lead to 404.

A quick workaround is to rename your vendor folder to "statics" for example and to replace "vendor" with "statics" in gulp.js and index.html.
