### ISSUE TITLE
scrolling on homepage with full paths not just anchor

### ISSUE THREAD

**Issue by Jimmi08** [BlackrockDigital/startbootstrap-freelancer#113]
At first - thank you for this theme.

Some CMS added full path to generated links so scrolling doesn't work. I needed to change freelancer.js this way:
```
    // jQuery for page scrolling feature - requires jQuery Easing plugin
    $('.page-scroll a').bind('click', function(event) {
        var $anchor = $(this);
        var url = $anchor.attr('href'), hash = "#" + url.split('#')[1]; 
        $('html, body').stop().animate({
	scrollTop: ($(hash).offset().top - 50)
        }, 1250, 'easeInOutExpo');
        event.preventDefault();
    });
```
Maybe you could consider to change this. I am not big friend with javascript, so maybe there is better solution. This way you can have multipage site with this theme.

**Comment by davidtmiller** [comment]
This is something that someone can add after the fact, but this is built as a one page theme.
