### ISSUE TITLE
Dark green color on clicking Send button

### ISSUE THREAD

**Issue by shreyash14s** [BlackrockDigital/startbootstrap-freelancer#122]
When I click the 'Send' it becomes dark green (#398439). 

![image](https://cloud.githubusercontent.com/assets/7680392/24578720/d2da7bb0-1703-11e7-9251-619eaa43ec00.png)

So I tried to search this color in freelancer.css file but couldn't find it. But found it in bootstrap.min.css. 

This color is coming from `btn-success`.

PS: I am running it on chrome-57, windows 10.

**Comment by shreyash14s** [comment]
I solved it and sent a pull request. Please take a look at it.

Thank you.

**Comment by davidtmiller** [comment]
This should be fixed now.
