### ISSUE TITLE
Star on hr doesn't appear under Edge

### ISSUE THREAD

**Issue by Silic0nS0ldier** [BlackrockDigital/startbootstrap-freelancer#125]
The star on `hr` doesn't appear when viewed via Edge. Other sites that use a similar style set work fine, but when those same styles are applied with freelancer, they fail.

This leads me to believe that there is a style rule somewhere causing conflicts. As to what style that is, I don't have a clue.

Screenshot demonstrating issue:
![image](https://cloud.githubusercontent.com/assets/17376090/26100343/f0046350-3a70-11e7-90a4-0805486ec8ff.png)

Site with `hr` styled using similar technique (see last): https://css-tricks.com/examples/hrs/

**Comment by pentyala** [comment]
I think that might be a bug on Edge, as the specified link doesn't work either on edge.

**Comment by davidtmiller** [comment]
I'll check into this and see if I can't get that star to appear on Edge.

**Comment by dwhiting10** [comment]
FYI in version 3.3.7-1 of this theme, the star doesn't not display in Chrome 61.  It displays just fine in Firefox.  Also of note is that the 4.0.0-beta.2 version of the theme displays correctly in Chrome 61 as well as Firefox.

**Comment by Silic0nS0ldier** [comment]
Can confirm that `4.0.0-beta.2` works on Edge. `3.3.7-1` is still a no go. Wonder if the fix could be back-ported... I don't need the fix anymore, but it looks like others do. I'll leave it up to @davidtmiller regarding whether or not the issue should be closed.

**Comment by utklasad** [comment]
The overflow property seems to have a new default value on the <hr> element.

It looks like the value changed from visible to hidden, so the icon is hidden. You can add overflow:visible to the <hr> element to show your icon again.

In short: Just add: overflow:visible; to the hr-classes and the icons will be visible again in Chrome 61+ and Edge.

**Comment by dwhiting10** [comment]
Thanks @utklasad.  That works.

**Comment by davidtmiller** [comment]
I rewrote the divider for this issue, so it no longer uses pseudo classes. Should be working cross-browser in the most recent update.
