### ISSUE TITLE
gulp less does not produce any output

### ISSUE THREAD

**Issue by jllopezpino** [BlackrockDigital/startbootstrap-freelancer#131]
I'm struggling to re-generate the css/freelancer.css and css/freelancer.min.css files.
gulp less is not producing any output.

An example:

```
$ git clone git@github.com:BlackrockDigital/startbootstrap-freelancer.git
$ cd startbootstrap-freelancer/
$ rm css/*
$ gulp less
```

And the result is an empty css/ folder:
```
$ ls -l css/
total 0
```

I'm using  gulp-less@3.3.2

Any idea of what could be causing this?

**Comment by graemelambert** [comment]
+1

I'm getting this problem too.

**Comment by nanomosfet** [comment]
Check out my pull request https://github.com/BlackrockDigital/startbootstrap-freelancer/pull/136. The changes in the gulp file address this problem.

**Comment by jllopezpino** [comment]
@nanomosfet I tried the changes in my private repository and it worked. Thanks.

**Comment by nanomosfet** [comment]
@jllopezpino Glad that worked!

**Comment by davidtmiller** [comment]
LESS was discontinued with #138
