### ISSUE TITLE
How to add redirect Thank you page after submit contact form

### ISSUE THREAD

**Issue by onmarketing** [BlackrockDigital/startbootstrap-freelancer#134]
Hi guys,

I would like to redirect thank you page from contact us page after submit contact form, does anyone knows how to add code php in contact_me.php?

Thanks,

Shaun.

**Comment by davidtmiller** [comment]
The `contact_me.js` file has the action in it to display the success message when the form is submitted successfully. You would need to go there and write a new function, replacing lines 33-46, with a function that redirects the user to a new page once a successful submission is made.
