### ISSUE TITLE
Readme doesn't include how to make changes to code

### ISSUE THREAD

**Issue by nanomosfet** [BlackrockDigital/startbootstrap-freelancer#140]
The readme seems to gloss over the details on how to make changes to this template.

**Comment by davidtmiller** [comment]
What part of the code are you looking for instructions on how to change?

**Comment by nanomosfet** [comment]
I didn't realize that LESS had been taken out and replaced with SASS. I guess I would just mention that running `gulp sass` will recompile your css. You do mention to look through the gulpfile so it is probably alright.

**Comment by davidtmiller** [comment]
I've added a list of the gulp tasks in the README as well. Hopefully this will suffice. I am planning to do some videos of how to edit themes and create some more comprehensive docs/instructions at some point, but I think this will do for now.

**Comment by nanomosfet** [comment]
Cool. Thanks for the awesome layouts!
