### ISSUE TITLE
PHP, Contact Me Form

### ISSUE THREAD

**Issue by larsonthekidrs** [BlackrockDigital/startbootstrap-freelancer#169]
The Contact me form is not working on my website. I am using Freelancer. Please Help.

**Comment by backtrackbaba** [comment]
Have you made any modifications in the PHP Script? 

You need to go into the PHP file and make the following changes

- Replace yourname@yourdomain.com with the email ID where you want the emails to be sent whenever somebody fills up the contact form

The rest of the fields can be kept the same. 

Let me know if this solves the issue.

**Comment by backtrackbaba** [comment]
Which Web Hosting Service are you currently using? Could you try contacting your web hosting service to open the SMTP Ports? 

If they aren't able to solve it, let me know. We'll try to bypass the issue in some way.

**Comment by larsonthekidrs** [comment]
I'm using GitHub pages. From what I've read all the ports are open.

**Comment by larsonthekidrs** [comment]
@backtrackbaba Does GH Pages block SMTP Ports?

**Comment by AbdullhRtima** [comment]
i have the same problem ???? what can i do now

**Comment by AbdullhRtima** [comment]
@larsonthekidrs  did you solved it ??

**Comment by AbdullhRtima** [comment]
@backtrackbaba  can you help plz ??

**Comment by larsonthekidrs** [comment]
@AbdullhRtima I have not yet solved it. The support is almost none... I'm still working on this in my free time.

**Comment by AbdullhRtima** [comment]
because i almost have no time for it so if you solve it plz  mention me

**Comment by larsonthekidrs** [comment]
@backtrackbaba Do you know of a way to get this working?
