### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [BlackrockDigital/startbootstrap-freelancer#171]
Hi,

We got an [issue](https://github.com/cdnjs/cdnjs/pull/12442) to update cdnjs hosting of your library to v4.0.0. However, there is no git tag for this new version on git repo, but on npm only. 
Could you please add git tag of v4.0.0 to git repo.
Thanks

**Comment by davidtmiller** [comment]
This should be fixed up now - `package.json` has been updated.

**Comment by sashberd** [comment]
@davidtmiller Nothing was happend

**Comment by davidtmiller** [comment]
Okay I just looked at the CDNJS and it looks like things weren't auto-updating after the 4.0+ releases. What do I need to add to the `package.json` on CDNJS?

**Comment by sashberd** [comment]
@davidtmiller just add git tag with version 4.0 to your git repo

**Comment by sashberd** [comment]
git tag v4.0
git push -a
I think this is the flow

**Comment by davidtmiller** [comment]
I think this should be fixed now - I was not tagging things properly but now I am. Sorry about the confusion!

**Comment by sashberd** [comment]
@davidtmiller Thanks.
