### ISSUE TITLE
Contact form - add checkbox checkbox acceptance

### ISSUE THREAD

**Issue by kanlukasz** [BlackrockDigital/startbootstrap-freelancer#172]
Hello,

Please, add checkbox acceptance in php form
Ssometimes it's required because of some rules or GPDR (important!)

**Comment by Pielgrin** [comment]
I will work on this

**Comment by malik97160** [comment]
I am working on this @Pielgrin.

**Comment by grantespo** [comment]
I solved this. I will post soon

**Comment by kanlukasz** [comment]
> 
> 
> I solved this. I will post soon

Ok great, so i close ticket
