### ISSUE TITLE
This project requires global installation of gulp.

### ISSUE THREAD

**Issue by nanomosfet** [BlackrockDigital/startbootstrap-freelancer#173]
I generally do not like global installations with node.js. In my own fork I have added 
```
"scripts": {
        "gulp": "gulp"
    }
```
So that I can run gulp without installing globally using `npm run gulp`. I could make a pull request for the package.json file if you would like.

**Comment by davidtmiller** [comment]
I have a `npm start` script at this point which will run the gulp dev task
