### ISSUE TITLE
add reCAPTCHA to contact form

### ISSUE THREAD

**Issue by BrettMcGregor** [BlackrockDigital/startbootstrap-freelancer#178]
I feel bad asking for a feature on something that is free. But on the off chance that someone else has already done this, please let me know/share your code!

In the meantime, I will try to figure out how to do it myself.

**Comment by malik97160** [comment]
I am working on it

**Comment by grantespo** [comment]
Any update on this?

**Comment by nathanaelytj** [comment]
I've integrated Google reCAPTHCA v2 support at this pull request: #188

**Comment by davidtmiller** [comment]
Thanks for the addition, but this is a custom feature that I would want to leave up to the user, but they can use that pull request as a guide if they want to add this feature.
