### ISSUE TITLE
Navigation Menu button hover color style is missing or not honored in freelancer.css

### ISSUE THREAD

**Issue by awattar** [BlackrockDigital/startbootstrap-freelancer#185]
Currently hover color of Menu button for narrow screens does not meet the style of other buttons on page (like contact me form Send button). I also couldn't find a way of changing it through freelancer.css.

**Comment by awattar** [comment]
I was able to fix it by changing following files (making as little as possible changes)

- index.html - remove bg_primary class, add btn btn-primary classes to Menu button

from

      <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded"

to

      <button class="navbar-toggler navbar-toggler-right text-uppercase btn btn-primary text-white rounded"

- freelancer.css - remove btn class, add missing important! to btn-primary selectors

from

```
.btn {
  border-width: 2px;
}

...

.btn-primary:hover, .btn-primary:focus, .btn-primary:active {
  background-color: #128f76;
  border-color: #128f76;
}
```

to

```
.btn-primary:hover, .btn-primary:focus, .btn-primary:active {
  background-color: #128f76 !important;
  border-color: #128f76 !important;
}
```

**Comment by davidtmiller** [comment]
Rewrote some of this stuff in the most recent update so this should no longer be an issue.
