### ISSUE TITLE
Contact Form HELP!!!

### ISSUE THREAD

**Issue by sjohnson2019** [BlackrockDigital/startbootstrap-freelancer#195]
Hii Guys, 

so i do now know any PHP, i am a ruby developer but i wanted to use this template as my page to try and attract freelance work. 

but i am getting a server error with the contact form. is there any pre-requisites to set up? 

Many Thanks

**Comment by kaashu** [comment]
I'm having the same issue with this was hoping to find a solution here! :(

**Comment by davidtmiller** [comment]
https://stackoverflow.com/questions/24644436/php-mail-function-doesnt-complete-sending-of-e-mail#

Take a look at this post on stackoverflow - hopefully this helps!
