### ISSUE TITLE
Contact Form issue

### ISSUE THREAD

**Issue by JulianG97** [BlackrockDigital/startbootstrap-freelancer#201]
Hello!

I changed $to in mail/contact_me.php to my email, but it still gives me the following error:
`Sorry Julian, it seems that my mail server is not responding. Please try again later!`
Do I need to change any other values somewhere else?

Thanks in advance!

**Comment by kaashu** [comment]
I'm having the same issue! Hope someone guides us to a solution!

**Comment by bneelon85** [comment]
Likewise!

**Comment by zaineb882** [comment]
me too :-1:

**Comment by davidtmiller** [comment]
The top answer on this stackoverflow post is better than anything I could troubleshoot - check it out here https://stackoverflow.com/questions/24644436/php-mail-function-doesnt-complete-sending-of-e-mail#
