### ISSUE TITLE
Getting Multiple errors

### ISSUE THREAD

**Issue by ezequias** [BlackrockDigital/startbootstrap-freelancer#207]
I am getting multiple erros like you can see in the files below:

![image](https://user-images.githubusercontent.com/539561/57879983-0e784780-77f4-11e9-9fb8-6385d4d4be72.png)

![image](https://user-images.githubusercontent.com/539561/57879909-e0930300-77f3-11e9-9208-d83512611b1e.png)

I am using DJANGO to run my application.

Ezequias

**Comment by maan** [comment]
Err.. looks like you didn't load some JS first?

**Comment by davidtmiller** [comment]
It looks like the Bootstrap JS is not loading - make sure Bootstrap is loading the JS it needs
