### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by originalls** [BlackrockDigital/startbootstrap-freelancer#221]
I am creating a Discord Bot with GitHub and Heroku. I am getting error when i run my app. It says "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command".

**Comment by rohattunaciftci** [comment]
My logs are
`-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  8.10.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 8.10.0...
       Downloading and installing node 8.10.0...
       Using default npm version: 5.6.0
       
-----> Restoring cache
       - node_modules
       
-----> Installing dependencies
       Installing node modules (package.json)
       up to date in 0.28s
       
-----> Build
       
-----> Pruning devDependencies
       Skipping because npm 5.6.0 sometimes fails when running 'npm prune' due to a known issue
       https://github.com/npm/npm/issues/19356
       
       You can silence this warning by updating to at least npm 5.7.1 in your package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version
       
-----> Caching build
       - node_modules
       
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types     -> worker
       Default types for buildpack -> web
-----> Compressing...
       Done: 17.6M
-----> Launching...
       Released v7
       https://sectorv.herokuapp.com/ deployed to Heroku`

**Comment by davidtmiller** [comment]
This doesn't look relevant to this theme.
