### ISSUE TITLE
IE 9 Contact form issue

### ISSUE THREAD

**Issue by mpsrig** [BlackrockDigital/startbootstrap-freelancer#31]
The contact form placeholders do not work on IE 9 at all. Even on IE 8, they show the placeholder, it just doesn't look as pretty.

Scroll to the bottom of the screenshot to see:

![win7_ie_9 0](https://cloud.githubusercontent.com/assets/11206336/7213516/bb170dfa-e54f-11e4-8967-8c2787914744.png)

IE 9 is a pretty modern browser.

How can I/we get this working? even if it's just a basic text label override.

**Comment by MichaelPehl** [comment]
IE9 a modern browser? Not at all.

Try using a plugin like https://github.com/mathiasbynens/jquery-placeholder
