### ISSUE TITLE
[FEATURE] Addition of Dark mode

### ISSUE THREAD

**Issue by shreyas-a-s** [BlackrockDigital/startbootstrap-freelancer#336]
Hi there!

I am using this template for my personal portfolio website and I had the idea of implementing a dark mode for my site. Then I thought it would be great if I could contribute to the project itself so that the community also gets the benefit.

Let me know whether this is something that is in the scope of the project. If yes and given the opportunity, I would love to do a PR.

**Comment by JoachimRohde** [comment]
3 years ago someone had the same question: https://github.com/StartBootstrap/startbootstrap-freelancer/issues/296

**Comment by shreyas-a-s** [comment]
@JoachimRohde Thanks for the heads up and the link to the issue. I didn't know repository with a dark mode did exist. I'm gonna make my dark mode off of that. I'm closing the issue.
