### ISSUE TITLE
Portfolio - new section format problem

### ISSUE THREAD

**Issue by how-i-roll** [BlackrockDigital/startbootstrap-freelancer#36]
I've almost successfully divided the portfolio grid into two sections, and it looks OK unless I want the navigation to work right. As soon as I change the new section name from section id="portfolio" 
to section id="coaching" so navigation can find it, it breaks everything. 

![portfolio](https://cloud.githubusercontent.com/assets/12039951/7600789/9b66061c-f8d4-11e4-8425-62518f32ad9e.JPG)

I've searched all the .css and .less code for references to "portfolio" and addressed everything I could find. Core bootstrap is bootswatch 3.3.4+1.

**Comment by floriansmakaj21** [comment]
Hi there, I know exactly how you feel I have the same problem. I have tried to look everywhere as well but no luck so far.

**Comment by davidtmiller** [comment]
This should be fixed up now.
