### ISSUE TITLE
Proper attribution

### ISSUE THREAD

**Issue by elizalive** [BlackrockDigital/startbootstrap-freelancer#39]
I am using the starbootstrap-freelancer theme for my portfolio site, and I want to make sure I properly attribute. Should I credit IronSummitMedia in the code or somewhere on the page so the user can see it? Sorry if this is a newbie question.

**Comment by MichaelPehl** [comment]
http://startbootstrap.com/help/ - read Copyright and License

**Comment by potherca** [comment]
@MichaelPehl You could have taken the effort to just quote the source and save other people the effort :wink: 

Quoting from the _Copyright and License_ section of the [StartBootstrap help page](http://startbootstrap.com/help/ ):

> Start Bootstrap is licensed under the Apache License, Version 2.0. Our free themes and templates that you can download on our site are open source, and are free to use, even commercially. Additionally, **attribution is not required** if you use our templates. All we ask is that if you like Start Bootstrap, be sure to share our website with your friends! You can view a copy of the license in our GitHub repository.

**Comment by davidtmiller** [comment]
It's MIT at this point, so use it for whatever!
