### ISSUE TITLE
fb meta tag

### ISSUE THREAD

**Issue by lloricode** [BlackrockDigital/startbootstrap-freelancer#40]
when i want to share the website to facebook, i want to auto select image and text, so how to do that? hmm thanks :)

**Comment by jdpenuliar** [comment]
i also have this problem. please help or email me at jaydz.penuliar@gmail.com

**Comment by MichaelPehl** [comment]
Not a theme "error" or problem. Read about Open Graph ... e.g. http://stackoverflow.com/questions/1138460/how-does-facebook-sharer-select-images-and-other-metadata-when-sharing-my-url

**Comment by jdpenuliar** [comment]
thank you very much

**Comment by davidtmiller** [comment]
Yes, check out the open graph protocol on Facebook's developers site.
