### ISSUE TITLE
Social icons not showing up

### ISSUE THREAD

**Issue by sagarmrey** [BlackrockDigital/startbootstrap-freelancer#42]
![screenshot-ironsummitmedia](https://cloud.githubusercontent.com/assets/8036205/7980486/8cdec414-0ac5-11e5-8560-206e305cb55d.jpg)
The social icons under the 'Around the web' are not opening.

**Comment by toubou91** [comment]
I can verify that I reproduced this issue in the past, but I wasn't able to find a workaround for this.
Seemed like it was a browser issue for me (Chrome), but I'm not facing it any more.

Nevertheless, it would be great if someone provided an explanation of this attitude :) .

**Comment by Wferr** [comment]
Could be happening because of a adblock  like extension?

**Comment by bencomeau** [comment]
@Wferr Yes, it's likely that. See this thread below regarding the issue via Font Awesome who generates the icons used in the theme.

https://github.com/FortAwesome/Font-Awesome/issues/1799

**Comment by MichaelPehl** [comment]
Your "error" has nothing to do with this theme itself.

**Comment by potherca** [comment]
Could be easily resolved by implementing the workaround suggested in the issue that is linked above:

> To work around this, you'll need to modify the social icon class names.

**Comment by davidtmiller** [comment]
These should be fixed now.
