### ISSUE TITLE
Configuring email

### ISSUE THREAD

**Issue by Jzarecta** [BlackrockDigital/startbootstrap-freelancer#47]
I tried to update my email and even create the path to the mail/contact_me.php however I never got the email. 

Reading the code, I dont see a form pointing to the php. Unless is using AJAX, I wonder how to verify the location of the file.

**Comment by toubou91** [comment]
Hey @Jzarecta ,

I suppose <a href="http://stackoverflow.com/a/32830798/2486904" target="_blank">this</a> answer will help you.

**Comment by davidtmiller** [comment]
Thanks @toubou91
