### ISSUE TITLE
Is there a vector version of the profile.png?

### ISSUE THREAD

**Issue by moorepants** [BlackrockDigital/startbootstrap-freelancer#50]

**Comment by iblancasa** [comment]
I don't know buy I created this https://mega.nz/#!kpA0EDwT!cv6nZez2lxCIgbSBFHgXynfoe74KZNd81DFwuWAFFcM

I hope this will be useful for you @moorepants

**Comment by moorepants** [comment]
Thanks. I'll trade you for a female version: https://gist.github.com/moorepants/7a10844b6b7b264b5ea0

**Comment by davidtmiller** [comment]
Thanks for the tips. No there isn't a vector version right now but I may replace it wit an SVG at some point in the future.
