### ISSUE TITLE
Around the Web button display maps poorly in production

### ISSUE THREAD

**Issue by swillio** [BlackrockDigital/startbootstrap-freelancer#51]
Viewing the site in my local environment shows that these buttons look and operate fine. However, the site I'm basing this template off of doesn't seem to respond well while it's hosted on a live webserver: http://andreacazares.com/

Every button is missing its respective icon, with the exception of the last button. Though this button is also lower than the rest for some reason:

It looks to be the same with the original freelancer theme as well: http://ironsummitmedia.github.io/startbootstrap-freelancer/

**Comment by davidtmiller** [comment]
This should be fixed now. Nice site!
