### ISSUE TITLE
New menu item

### ISSUE THREAD

**Issue by dzcatic** [BlackrockDigital/startbootstrap-freelancer#53]
I was wondering where should I add in js once I added new item in main menu? I have added new menu but I want to navigate to that div after click, as it works on other menus on theme.
Could someone give me a hint?

**Comment by dzcatic** [comment]
I have solved the problem. This issue could be closed

**Comment by toubou91** [comment]
Hello,

perfect.

I suppose you could close the issue by yourself.
Isn't there a "Close issue" button for you?

![image](https://cloud.githubusercontent.com/assets/5684688/11470563/77a5089a-9767-11e5-804f-add6d96ed366.png)
