### ISSUE TITLE
Nav dropdown broken in hamburger menu

### ISSUE THREAD

**Issue by bfrederix** [BlackrockDigital/startbootstrap-freelancer#55]
See issue here: http://stackoverflow.com/questions/29138099/bootstrap-3-dropdown-menu-not-working-for-smaller-screen-size-mobile-tablet/29592932

Dropdowns are broken for hamburger menu items. Fix is to change freelancer.js selecter to use the li class "page-scroll":

$('.navbar-collapse ul li.page-scroll a').cl[...]

**Comment by davidtmiller** [comment]
This should be fixed now.
