### ISSUE TITLE
calling all html gurus for help

### ISSUE THREAD

**Issue by cyberpay** [BlackrockDigital/startbootstrap-freelancer#56]
guys new to html and all web content having a question 
i want only circular icons to display in the portfolio section (no magnifying and square background as shown in this screen grab http://prntscr.com/9c0ezy) so i deleted some code from index file and successfully accomplished it. 
however now how to reduce spacing in between 2 icons and is there any way we can use background image in project description ? http://prntscr.com/9c0ezy

**Comment by davidtmiller** [comment]
You can add margin and padding to the icons using CSS to change how they are spaced out.
