### ISSUE TITLE
how do i change the color over the hover portfolio?

### ISSUE THREAD

**Issue by ejcollazo** [BlackrockDigital/startbootstrap-freelancer#57]
i am changing the colors throughout

**Comment by kesselhocj24** [comment]
Under the freelance.css

#portfolio .portfolio-item .portfolio-link .caption {
    position: absolute;
    width: 100%;
    height: 100%;
    opacity: 0;
    background: rgba(209,169,0,0.90); ***
    -webkit-transition: all ease .5s;
    -moz-transition: all ease .5s;
    transition: all ease .5s;
}

**Comment by davidtmiller** [comment]
The best way to do it is to change the LESS, but you can also do it in the CSS as @kesselhocj24 described.
