### ISSUE TITLE
portfolio-modal

### ISSUE THREAD

**Issue by aliakbars** [BlackrockDigital/startbootstrap-freelancer#6]
After using Bootstrap 3.3.0, there is a <div> overlaying the project after clicking the project picture. I try to change the bootstrap file with the one on Jekyll project, and then it became normal again.
![screenshot from 2014-11-03 11 55 38](https://cloud.githubusercontent.com/assets/7055994/4878669/bc813d4e-6315-11e4-9c86-4ccc8cdf13e1.png)

**Comment by d88naimi** [comment]
Hello @davidtmiller amazing amazing theme thank you for all your hard work. I just stumbled over the modal issue and have tried the .modal-backdrop.in {opacity: 0;} and display none also tried changing the bootstrap version number to 4.0, then the layout gets all whacky. Any new solutions? thank you
