### ISSUE TITLE
freelancer on gh-pages

### ISSUE THREAD

**Issue by RobyRemzy** [BlackrockDigital/startbootstrap-freelancer#65]
hi guys,
i'm kind of lost to render the master repo to a gh-pages one,
do i have to grunt things? and how? can you explain to me how things can get done please?

thanks

**Comment by davidtmiller** [comment]
If you have a GitHub repo set up you just need to make a new branch called 'gh-pages' and set it to be the default branch. Then GitHub will automatically generate a site from the contents of the repo.

**Comment by RobyRemzy** [comment]
thanks but, i may miss something...
i have a master repo ready to be deploy.
i make a new branch gh-pages.
when set the gh-pages content was the same as the master repo.
i set the branch gh-pages as the default branch.
when i go to http://robyremzy.github.io/qsscore/ still no css or modals working.

**Comment by davidtmiller** [comment]
Hmm, interesting. Are you using something like Jekyll? If so you might need to change your baseurl to allow for the CSS and custom JS to load properly.

**Comment by iblancasa** [comment]
I think it will be easier if you show your code...

**Comment by RobyRemzy** [comment]
hi yep sure , i deleted all this morning but i just do the same steps to show them here:
https://github.com/RobyRemzy/ebscore
http://robyremzy.github.io/ebscore/

i have no clue, i hope it's a good sign and this is something dumb :cat2:

**Comment by iblancasa** [comment]
Problem is: you are using absolute paths.
For example, you wrote: "/style.css". Style is in "http://robyremzy.github.io/ebscore/style.css" and you are looking for it in "http://robyremzy.github.io/style.css"

**Comment by RobyRemzy** [comment]
oh right! but do you mean into the _site folder because this one is re write automatically

**Comment by RobyRemzy** [comment]
omg ok i opened my console with firefox and saw the lake of fetch all the .js and .css
how can i mod that? into the _includes/head.html or the _config.yml

**Comment by iblancasa** [comment]
Sorry. I cannot see this before. You has a pull request :D

**Comment by RobyRemzy** [comment]
thanks, it's all good now, well i believe this tweak have to be done every time to be deployed on gh-pages for good? but it's ok on user.github.io, right!

**Comment by iblancasa** [comment]
No. Now, you only has to change your _config.yml file :D

**Comment by RobyRemzy** [comment]
great! thank you guys. I believe this topics is close!
