### ISSUE TITLE
http in jquery-easing script url

### ISSUE THREAD

**Issue by flortsch** [BlackrockDigital/startbootstrap-freelancer#69]
Hello,

first of all I wanna thank you for your great work. I tried out your theme and I love it :)

I tried the theme on a web server which forces https and I noticed that the reference to the jquery-easing script uses http. This makes web browsers show an icon that there are insecure elements on the website.

Maybe it's not a problem for people using the theme on a http site, I just wanted to mention it for people, who use it on web servers which support or force https. Since other stuff on the site like fonts is also references with https, the url for the jquery-easing script could be simply set to https. It works, the server which serves the script supports it.

Best regards
Florian

**Comment by jesseke55** [comment]
You could use // or / for those urls

**Comment by davidtmiller** [comment]
I can use HTTPS on the CDN in the future, perhaps I'll go and change that up...
