### ISSUE TITLE
Accent problem

### ISSUE THREAD

**Issue by Grafikx** [BlackrockDigital/startbootstrap-freelancer#76]
Hello,
I meet an accent problem with fonction mail . The emails received see all their accents replaced by symbols . Would you know what code do I have added to correct this problem ?
Thank you in advance !

**Comment by Grafikx** [comment]
I finally found a solution with the use of :
$headers = "Content-Type: text/plain; charset=UTF-8;" . "\r\n";
But if you offer me better I'm interested. ;)

**Comment by davidtmiller** [comment]
This looks like a good fix for your purposes, I don't have anything better to offer!
