### ISSUE TITLE
Email form server is not responding

### ISSUE THREAD

**Issue by BillGR17** [BlackrockDigital/startbootstrap-freelancer#91]
The email form doesnt work for me can someone explain why?
with or without any changes i get the same error.

**Comment by Xonshiz** [comment]
It's a php script and sending an email sometimes require a mail server to be configured. Maybe that's why it is not working.

**Comment by isaacbazan** [comment]
You have to log into your cpanel and see if your server is allowed to send smtp emails. Also, check the configuration of your php.ini file. @BillGR17
